### ISSUE TITLE
Fix security vulnerability

### ISSUE THREAD

**Issue by woltob** [SoftwareBrothers/adminjs-design-system#24]
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
No fix available
node_modules/quill
  @admin-bro/design-system  >=1.7.0-beta.1
  Depends on vulnerable versions of quill
  node_modules/@admin-bro/design-system
  @adminjs/design-system  *
  Depends on vulnerable versions of quill
  node_modules/@adminjs/design-system
    adminjs  *
    Depends on vulnerable versions of @adminjs/design-system
    node_modules/adminjs
      @adminjs/express  *
      Depends on vulnerable versions of adminjs
      node_modules/@adminjs/express
      @adminjs/mikroorm  *
      Depends on vulnerable versions of adminjs
      node_modules/@adminjs/mikroorm
      @adminjs/nestjs  *
      Depends on vulnerable versions of adminjs
      node_modules/@adminjs/nestjs

12 vulnerabilities (7 moderate, 5 high)

Thank you for updating the packages.

**Comment by dziraf** [comment]
This is unfixable since Quill is not being updated anymore, we will probably switch to another text editor soon/in the future. This vulnerability shouldn't affect you as long as you don't use richtext editor for your properties.
